[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32@6.12.0
board = esp32dev
framework = arduino

; Conservative flashing settings for classic ESP32-WROOM development boards.
upload_speed = 406800
#board_build.flash_mode = dio
monitor_speed = 115200
monitor_dtr = 0
monitor_rts = 0

; UART0 is a debug console. The tuner protocol uses software serial on GPIO21/22.
build_flags = -DCORE_DEBUG_LEVEL=0

lib_deps =
    https://github.com/plerup/espsoftwareserial.git#8.2.0
upload_port = COM5
#monitor_port = COM5

